- include: reset.yml

- include: pause.yml
    message="Pause for the hardware reset to kick in"

- include: wait.yml

- include: bootstrap.yml

- include: pause.yml
    message="Pause for the reboot to kick in"
    seconds=60

- include: wait.yml

- include: pause.yml
    message="Let the server breathe a little"

- name: Post installation update
  include_role: name=packages tasks_from=update
